<?php

namespace app\models;

use Faker\Core\Uuid;
use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "country".
 *
 * @property int $id
 * @property string|null $uid
 * @property string|null $name_ru
 * @property string|null $name_en
 * @property boolean $deleted
 */
class Country extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'country';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'name_ru', 'name_en'], 'string', 'max' => 255],
            [['uid'], 'unique'],
            [['name_ru'], 'unique'],
            [['name_en'], 'unique'],
            [['deleted'], 'boolean']
        ];
    }


    public function beforeSave($insert)
    {
        if (!$this->uid) {
            $this->uid = new Expression('UUID()');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave ($insert, $changedAttributes)
    {
        if ($insert) {
            $this->refresh();
        }
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'uid' => 'Uid',
            'name_ru' => 'Name Ru',
            'name_en' => 'Name En',
        ];
    }
}
